_BASE_: ./maskformer2_R50_bs16_90k.yaml
MODEL:
  BACKBONE:
    NAME: "D2SwinTransformer"
  SWIN:
    EMBED_DIM: 192
    DEPTHS: [2, 2, 18, 2]
    NUM_HEADS: [6, 12, 24, 48]
    WINDOW_SIZE: 12
    APE: False
    DROP_PATH_RATE: 0.3
    PATCH_NORM: True
    PRETRAIN_IMG_SIZE: 384
  WEIGHTS: "model_weights/swin_large_patch4_window12_384_22k.pkl"
  PIXEL_MEAN: [53.1165, 54.1620, 54.7230]  #* important; divide by 255
  PIXEL_STD: [68.0595, 68.8500, 69.1305]  #* important; divide by 255
  MASK_FORMER:
    NUM_OBJECT_QUERIES: 100
  SEM_SEG_HEAD:
    IGNORE_VALUE: 255
    NUM_CLASSES: 8  #* important
DATASETS:
  TRAIN: ("allo_train",) #TODO: change this
  TEST: ("allo_seg_val",) #TODO: change this
SOLVER:
  IMS_PER_BATCH: 16  #* 4x4
  BASE_LR: 0.0001
  MAX_ITER: 90000
DATALOADER:
  NUM_WORKERS: 8  #* 4
TEST:
  EVAL_PERIOD: 100  #TODO: set it high enough so that it doesn't run during training

OUTPUT_DIR: './results/m2former_allo'