_BASE_: ./maskformer2_R50_bs16_90k.yaml
MODEL:
  BACKBONE:
    NAME: "D2SwinTransformer"
  SWIN:
    EMBED_DIM: 192
    DEPTHS: [2, 2, 18, 2]
    NUM_HEADS: [6, 12, 24, 48]
    WINDOW_SIZE: 12
    APE: False
    DROP_PATH_RATE: 0.3
    PATCH_NORM: True
    PRETRAIN_IMG_SIZE: 384
  WEIGHTS: "model_weights/model_allo_seg_test.pth"  #* change this
  PIXEL_MEAN: [53.1165, 54.1620, 54.7230]  #* important; divide by 255
  PIXEL_STD: [68.0595, 68.8500, 69.1305]  #* important; divide by 255
  MASK_FORMER:
    NUM_OBJECT_QUERIES: 100
  SEM_SEG_HEAD:
    IGNORE_VALUE: 255
    NUM_CLASSES: 9  #* important; K+1
INPUT:
  DATASET_MAPPER_NAME: "mask_former_allo" #*  "mask_former_allo"
DATASETS:
  TRAIN: ("allo_train",)
  TEST: ("allo_anomaly_val",) #* important
SOLVER:
  IMS_PER_BATCH: 16 #* important; 4x4
  BASE_LR: 0.00001
  MAX_ITER: 5000  #* important
  CHECKPOINT_PERIOD: 1000
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 0
  WEIGHT_DECAY: 0.05
DATALOADER:
  NUM_WORKERS: 8
TEST:
  EVAL_PERIOD: 1000 #* change this
ANOMALY_DETECTOR: "UNO"
OUTPUT_DIR: './results/UNO_allo'
SEED: 42