_BASE_: ./maskformer2_R50_bs16_90k.yaml
MODEL:
  BACKBONE:
    NAME: "D2SwinTransformer"
  SWIN:
    EMBED_DIM: 192
    DEPTHS: [2, 2, 18, 2]
    NUM_HEADS: [6, 12, 24, 48]
    WINDOW_SIZE: 12
    APE: False
    DROP_PATH_RATE: 0.3
    PATCH_NORM: True
    PRETRAIN_IMG_SIZE: 384
  # WEIGHTS: "model_weights/swin_large_patch4_window12_384_22k.pkl" #* change this
  WEIGHTS: "results/m2former_allo_fbseg/model_0000049.pth"
  PIXEL_MEAN: [36.924, 37.8675, 38.3265]
  PIXEL_STD: [54.0345, 54.5955, 54.7995]
  MASK_FORMER:
    NUM_OBJECT_QUERIES: 10
  SEM_SEG_HEAD:
    IGNORE_VALUE: 255
    NUM_CLASSES: 3  #* important
INPUT:
  DATASET_MAPPER_NAME: "mask_former_allo" #*  "mask_former_allo"
DATASETS:
  TRAIN: ("allo_train",)
  TEST: ("allo_val",)
SOLVER:
  IMS_PER_BATCH: 12 #* important
  BASE_LR: 0.00001
  MAX_ITER: 2000
  CHECKPOINT_PERIOD: 1000
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 0
  WEIGHT_DECAY: 0.05
DATALOADER:
  NUM_WORKERS: 0
TEST:
  EVAL_PERIOD: 100000  #TODO: set it high enough so that it doesn't run during training
ANOMALY_DETECTOR: "UNO"
OUTPUT_DIR: './results/m2former_allo_uno'