_BASE_: ../maskformer2_R50_bs16_90k.yaml
MODEL:
  BACKBONE:
    NAME: "D2DinoVisionTransformer"
  FREEZE_BACKBONE: True
  DINO_V2:
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  MASK_FORMER:
    NUM_OBJECT_QUERIES: 100
  SEM_SEG_HEAD: 
    NUM_CLASSES: 2 # K+1+no_object
  WEIGHTS: "model_weights/dinov2_converted_1024x1024_p16_backbone.pth"

INPUT:
  DATASET_MAPPER_NAME: "mask_former_semantic_traffic_uno_binary"
SOLVER:
  CHECKPOINT_PERIOD: 2000
  IMS_PER_BATCH: 4
  BASE_LR: 0.00001
  MAX_ITER: 16000
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 0
  WEIGHT_DECAY: 0.05

TEST:
  EVAL_PERIOD: 2000

DATASETS:
  TRAIN: ("mapillary_cityscapes_sem_seg_train", "cityscapes_fine_sem_seg_train")
  TEST: ("fs_laf_val", "road_anomaly")
DATALOADER:
  NUM_WORKERS: 4

ANOMALY_DETECTOR: "UNO"

OUTPUT_DIR: '/home/johnl/results/UNO-cityscapes_binary'

